### PR TITLE
Add --help and --version switch

### PR DESCRIPTION
**Pull request by MaT1g3R**
Addresses #8

### CODE REVIEW

**Comment by Chirag-Khandelwal** [comment]
why the seven spaces by the way?

**Comment by MaT1g3R** [comment]
It is to align the text, I tried using tab but it didn't do what I wanted. Is there a better way of doing it?

**Comment by Chirag-Khandelwal** [comment]
what do you want to align? it seems aligned to me...?
screen shot 2018-06-13 at 15 48 41
Sorry for so many questions. I just want to make sure we are on the same page. And if needed, I could implement new functions to ease up the formatting a bit :)

**Comment by MaT1g3R** [comment]
Because `--help` and `--version` are longer than `-s` for example

screen shot 2018-06-13 at 6 39 07 pm

**Comment by Chirag-Khandelwal** [comment]
ok I just made a commit. It adds (*) as padding for format strings.
So now, you can do, for example:
`display( "%*s", 5, "str" );`
This will give a padding of 5 to the string `str`, hence there will be 2 more spaces left.

For empty spaces, just use `%*` format string. Please give it a try and see if it works? I also have added a test for that in `tests/display_colored_padding.c`

By the way, **important note**: adding a fixed number of spaces does not fix the align issue. using the tab character, however, does ( only if the variation of number of spaces is within the range of length of tab character - usually 4 or 8 ) 😉 

I really appreciate all that you have done :)

**Comment by Chirag-Khandelwal** [comment]
oh don't change anything now. I have done the changes :)

**Comment by MaT1g3R** [comment]
Opps it seems like we changed it at the same time

**Comment by Chirag-Khandelwal** [comment]
lol yea :P it's ok I have corrected that. Thanks so much for helping :)

**Pull request merged**
